name: WinForms .NET Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore WinForms packages
        run: nuget restore DevOpsWinFormsDemo\DevOpsWinFormsDemo.sln

      - name: Restore Test packages
        run: nuget restore DevOpsWinFormsDemo.Tests\DevOpsWinFormsDemo.Tests.csproj

      - name: Build WinForms project
        run: msbuild DevOpsWinFormsDemo\DevOpsWinFormsDemo.csproj /p:Configuration=Release /p:Platform=AnyCPU

      - name: Build Test project
        run: msbuild DevOpsWinFormsDemo.Tests\DevOpsWinFormsDemo.Tests.csproj /p:Configuration=Release /p:Platform=AnyCPU

      - name: Show DLL files
        shell: pwsh
        run: |
          Get-ChildItem -Path . -Recurse -Filter "*.dll" | ForEach-Object {
            Write-Host $_.FullName
          }

      - name: Run tests
        shell: pwsh
        run: |
          $vstest = "${env:ProgramFiles}\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"

          Write-Host "===== Searching test DLL ====="

          $testDlls = Get-ChildItem -Path . -Recurse -Filter "DevOpsWinFormsDemo.Tests.dll" |
            Where-Object { $_.FullName -notlike "*\obj\*" }

          $testDlls | ForEach-Object { Write-Host $_.FullName }

          if ($testDlls.Count -eq 0) {
            Write-Error "No test DLLs found."
            exit 1
          }

          foreach ($dll in $testDlls) {
            Write-Host "Running tests in $($dll.FullName)"
            & $vstest $dll.FullName
          }