name: WinForms .NET Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: windows-2022

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v2

      - name: Restore WinForms packages
        run: nuget restore DevOpsWinFormsDemo\DevOpsWinFormsDemo.sln

      - name: Build WinForms project
        run: msbuild DevOpsWinFormsDemo\DevOpsWinFormsDemo.csproj /p:Configuration=Release /p:Platform=AnyCPU

      - name: Run tests
        run: dotnet test DevOpsWinFormsDemo.Tests\DevOpsWinFormsDemo.Tests.csproj --configuration Release --no-restore --logger trx